apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java_app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: java_app
    spec:
      imagePullSecrets:
        - name: ecrpullsecret
      containers:
        - name: java-app-container
          image: ${SECRET_ACC}.dkr.ecr.us-east-1.amazonaws.com/calculator:latest
          env:
        - name: SECRET_ACC
          valueFrom:
            secretKeyRef:
              name: account_info
              key: account_id
          ports:
            - containerPort: 8080
